name: Java CI/CD with Gradle

on: #언제 적용시킬것인가
  push: #push 발생시
    branches: ["main"] #이거 실행
  pull_request: #pr 발생시
    branches: ["main"] #이거 실행

permissions: 
  contents: read

jobs: # main브랜치에 push, pr이 일어났을때 실행  
  build:
    runs-on: ubuntu-20.04 #이거 기반으로

    steps: #이 순서에 따라 진행
    - uses: actions/checkout@v3 
            #무조건 써야함! 깃허브에 올린 리소스(파일, 디렉토리) 가져오는 역할

    - name: setup jdk11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

     #그래들 초기화
    - name: init with gradle
      uses: gradle/gradle-build-action@v2

		#실제 초기화 일어남
    - run: gradle init

    - name: Build with gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.5.1
        arguments: build 

    - name: docker image build
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/gradlesample01 .

    - name: docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: dockerhub push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/gradlesample01
